export type OdooUserLinkLabels = {
  connectedTitle: string;
  linkTitle: string;
  connectedDesc: string;
  linkDesc: string;
  statusConnected: string;
  statusReconnect: string;
  waitingAdmin: string;
  justLinkedTitle: string;
  justLinkedDesc: string;
  reconnectTitle: string;
  errorTitle: string;
  updateLink: string;
  editTitle: string;
  companyUrlHint: string;
  usernameSimple: string;
  passwordSimple: string;
  passwordKeep: string;
  passwordRequired: string;
  saveUpdate: string;
  saveSimple: string;
  saving: string;
  testSimple: string;
  formMissingOdoo: string;
  cancelEdit: string;
  openBrowser: string;
  openTasks: string;
  disconnect: string;
  disconnectTitle: string;
  disconnectDesc: string;
  disconnectCancel: string;
  disconnectConfirm: string;
  summaryAccount: string;
  summaryServer: string;
  summaryPassword: string;
  passwordSecured: string;
  summaryLinked: string;
  summarySync: string;
  neverSynced: string;
  summaryLastTest: string;
  connectedReady: string;
};

export function buildOdooUserLinkLabels(t: (key: string) => string): OdooUserLinkLabels {
  return {
    connectedTitle: t("integrations.odoo.connectedTitle"),
    linkTitle: t("integrations.odoo.linkTitle"),
    connectedDesc: t("integrations.odoo.connectedDesc"),
    linkDesc: t("integrations.odoo.linkDesc"),
    statusConnected: t("integrations.odoo.statusConnected"),
    statusReconnect: t("integrations.odoo.statusReconnect"),
    waitingAdmin: t("integrations.odoo.waitingAdmin"),
    justLinkedTitle: t("integrations.odoo.justLinkedTitle"),
    justLinkedDesc: t("integrations.odoo.justLinkedDesc"),
    reconnectTitle: t("integrations.odoo.reconnectTitle"),
    errorTitle: t("integrations.odoo.errorTitle"),
    updateLink: t("integrations.odoo.updateLink"),
    editTitle: t("integrations.odoo.editTitle"),
    companyUrlHint: t("integrations.odoo.companyUrlHint"),
    usernameSimple: t("integrations.odoo.usernameSimple"),
    passwordSimple: t("integrations.odoo.passwordSimple"),
    passwordKeep: t("integrations.odoo.passwordKeep"),
    passwordRequired: t("integrations.odoo.passwordRequired"),
    saveUpdate: t("integrations.odoo.saveUpdate"),
    saveSimple: t("integrations.odoo.saveSimple"),
    saving: t("integrations.odoo.saving"),
    testSimple: t("integrations.odoo.testSimple"),
    formMissingOdoo: t("integrations.formMissingOdoo"),
    cancelEdit: t("integrations.odoo.cancelEdit"),
    openBrowser: t("integrations.odoo.openBrowser"),
    openTasks: t("integrations.odoo.openTasks"),
    disconnect: t("integrations.odoo.disconnect"),
    disconnectTitle: t("integrations.odoo.disconnectTitle"),
    disconnectDesc: t("integrations.odoo.disconnectDesc"),
    disconnectCancel: t("integrations.odoo.disconnectCancel"),
    disconnectConfirm: t("integrations.odoo.disconnectConfirm"),
    summaryAccount: t("integrations.odoo.summaryAccount"),
    summaryServer: t("integrations.odoo.summaryServer"),
    summaryPassword: t("integrations.odoo.summaryPassword"),
    passwordSecured: t("integrations.odoo.passwordSecured"),
    summaryLinked: t("integrations.odoo.summaryLinked"),
    summarySync: t("integrations.odoo.summarySync"),
    neverSynced: t("integrations.odoo.neverSynced"),
    summaryLastTest: t("integrations.odoo.summaryLastTest"),
    connectedReady: t("integrations.odoo.connectedReady"),
  };
}
